// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file v1/api.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateRequest, CreateResponse, DeleteRequest, DeleteResponse, MoveRequest, MoveResponse, ReadRequest, ReadResponse } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.ArchiveService
 */
export const ArchiveService = {
  typeName: "v1.ArchiveService",
  methods: {
    /**
     * @generated from rpc v1.ArchiveService.Read
     */
    read: {
      name: "Read",
      I: ReadRequest,
      O: ReadResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.ArchiveService.Create
     */
    create: {
      name: "Create",
      I: CreateRequest,
      O: CreateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.ArchiveService.Move
     */
    move: {
      name: "Move",
      I: MoveRequest,
      O: MoveResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.ArchiveService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteRequest,
      O: DeleteResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

